name: Node.js CI

on:
  push:
    branches: [features/two-step-pipeline]
  pull_request:
    branches: [main]

env:
  BASEURL: ${{ vars.BASEURL }}
  USER: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - run: npm install

      - name: Smoke Tests
        run: npm run smoke

      - name: Regression Tests
        run: npm run regression
        continue-on-error: true
